version: "3.2"
services:
  cennznet:
    image: cennznet/cennznet:2.2.0-rc6
    volumes:
      - ./.cennznet/data:/mnt/data
    command:
      - --dev
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --base-path=/mnt/data
    ports:
      - "9933:9933"
      - "9944:9944"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.rabbitmq/data/:/var/lib/rabbitmq/
      - ./.rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./.mongodb/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

networks:
  rabbitmq_go_net:
    driver: bridge
