name: "Create new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-release:
    name: "New release branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.version }}

      - name: Update version
        run: |
          npm version ${{ github.event.inputs.version }}

      - name: Create pull request to `main`
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/v${{ github.event.inputs.version }}
          base: 'main'
          commit-message: Prep for v${{ github.event.inputs.version }}
          title: Release version ${{ github.event.inputs.version }}
