name: "Create new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-release:
    name: "New release branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.version }}

      - name: Update version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit changelog and manifest files
        run: |
          git add package.json
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Create pull request to `main`
        uses: thomaseizinger/create-pull-request@1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.version }}
          base: main
          title: Release version ${{ github.event.inputs.version }}
